#############################################################################
# Makefile for building: SecureVault.app/Contents/MacOS/SecureVault
# Generated by qmake (3.1) (Qt 5.15.15)
# Project:  securevault.pro
# Template: app
# Command: /opt/local/libexec/qt5/bin/qmake -o Makefile securevault.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/local/include -I/opt/local/include/openssl -I/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers -I/opt/local/libexec/qt5/lib/QtGui.framework/Headers -I/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers -I/opt/local/libexec/qt5/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/local/libexec/qt5/mkspecs/macx-clang -F/opt/local/libexec/qt5/lib
QMAKE         = /opt/local/libexec/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/local/libexec/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/local/libexec/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SecureVault1.0.0
DISTDIR = /Users/gowrisankara/Desktop/SV/SV-PROJECT/.tmp/SecureVault1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/opt/local/libexec/qt5/lib -L/opt/local/lib -lssl -lcrypto -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		rojer_encrypt.cpp qrc_resources.cpp \
		moc_sv_main.cpp
OBJECTS       = main.o \
		rojer_encrypt.o \
		qrc_resources.o \
		moc_sv_main.o
DIST          = /opt/local/libexec/qt5/mkspecs/features/spec_pre.prf \
		/opt/local/libexec/qt5/mkspecs/qdevice.pri \
		/opt/local/libexec/qt5/mkspecs/features/device_config.prf \
		/opt/local/libexec/qt5/mkspecs/common/unix.conf \
		/opt/local/libexec/qt5/mkspecs/common/mac.conf \
		/opt/local/libexec/qt5/mkspecs/common/macx.conf \
		/opt/local/libexec/qt5/mkspecs/common/sanitize.conf \
		/opt/local/libexec/qt5/mkspecs/common/gcc-base.conf \
		/opt/local/libexec/qt5/mkspecs/common/gcc-base-mac.conf \
		/opt/local/libexec/qt5/mkspecs/common/clang.conf \
		/opt/local/libexec/qt5/mkspecs/common/clang-mac.conf \
		/opt/local/libexec/qt5/mkspecs/qconfig.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/libexec/qt5/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt5/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt5/mkspecs/macx-clang/qmake.conf \
		/opt/local/libexec/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/opt/local/libexec/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt5/mkspecs/features/toolchain.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/toolchain.prf \
		/opt/local/libexec/qt5/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt5/mkspecs/features/resolve_config.prf \
		/opt/local/libexec/qt5/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/mac.prf \
		/opt/local/libexec/qt5/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt5/mkspecs/features/qt.prf \
		/opt/local/libexec/qt5/mkspecs/features/resources_functions.prf \
		/opt/local/libexec/qt5/mkspecs/features/resources.prf \
		/opt/local/libexec/qt5/mkspecs/features/moc.prf \
		/opt/local/libexec/qt5/mkspecs/features/unix/opengl.prf \
		/opt/local/libexec/qt5/mkspecs/features/uic.prf \
		/opt/local/libexec/qt5/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt5/mkspecs/features/qmake_use.prf \
		/opt/local/libexec/qt5/mkspecs/features/file_copies.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/asset_catalogs.prf \
		/opt/local/libexec/qt5/mkspecs/features/testcase_targets.prf \
		/opt/local/libexec/qt5/mkspecs/features/exceptions.prf \
		/opt/local/libexec/qt5/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt5/mkspecs/features/lex.prf \
		securevault.pro login.h \
		sv_main.h \
		rojer_home.h \
		rojer_encrypt.h main.cpp \
		rojer_encrypt.cpp
QMAKE_TARGET  = SecureVault
DESTDIR       = 
TARGET        = SecureVault.app/Contents/MacOS/SecureVault

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/gowrisankara/Desktop/SV/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/gowrisankara/Desktop/SV/SV-PROJECT/securevault.pro


include /opt/local/libexec/qt5/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

SecureVault.app/Contents/MacOS/SecureVault:  $(OBJECTS)  
	@test -d SecureVault.app/Contents/MacOS/ || mkdir -p SecureVault.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: securevault.pro /opt/local/libexec/qt5/mkspecs/macx-clang/qmake.conf /opt/local/libexec/qt5/mkspecs/features/spec_pre.prf \
		/opt/local/libexec/qt5/mkspecs/qdevice.pri \
		/opt/local/libexec/qt5/mkspecs/features/device_config.prf \
		/opt/local/libexec/qt5/mkspecs/common/unix.conf \
		/opt/local/libexec/qt5/mkspecs/common/mac.conf \
		/opt/local/libexec/qt5/mkspecs/common/macx.conf \
		/opt/local/libexec/qt5/mkspecs/common/sanitize.conf \
		/opt/local/libexec/qt5/mkspecs/common/gcc-base.conf \
		/opt/local/libexec/qt5/mkspecs/common/gcc-base-mac.conf \
		/opt/local/libexec/qt5/mkspecs/common/clang.conf \
		/opt/local/libexec/qt5/mkspecs/common/clang-mac.conf \
		/opt/local/libexec/qt5/mkspecs/qconfig.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/libexec/qt5/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt5/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt5/mkspecs/macx-clang/qmake.conf \
		/opt/local/libexec/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/opt/local/libexec/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt5/mkspecs/features/toolchain.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/toolchain.prf \
		/opt/local/libexec/qt5/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt5/mkspecs/features/resolve_config.prf \
		/opt/local/libexec/qt5/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/mac.prf \
		/opt/local/libexec/qt5/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt5/mkspecs/features/qt.prf \
		/opt/local/libexec/qt5/mkspecs/features/resources_functions.prf \
		/opt/local/libexec/qt5/mkspecs/features/resources.prf \
		/opt/local/libexec/qt5/mkspecs/features/moc.prf \
		/opt/local/libexec/qt5/mkspecs/features/unix/opengl.prf \
		/opt/local/libexec/qt5/mkspecs/features/uic.prf \
		/opt/local/libexec/qt5/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt5/mkspecs/features/qmake_use.prf \
		/opt/local/libexec/qt5/mkspecs/features/file_copies.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt5/mkspecs/features/mac/asset_catalogs.prf \
		/opt/local/libexec/qt5/mkspecs/features/testcase_targets.prf \
		/opt/local/libexec/qt5/mkspecs/features/exceptions.prf \
		/opt/local/libexec/qt5/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt5/mkspecs/features/lex.prf \
		securevault.pro \
		resources.qrc \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/local/libexec/qt5/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		/opt/local/libexec/qt5/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile securevault.pro
/opt/local/libexec/qt5/mkspecs/features/spec_pre.prf:
/opt/local/libexec/qt5/mkspecs/qdevice.pri:
/opt/local/libexec/qt5/mkspecs/features/device_config.prf:
/opt/local/libexec/qt5/mkspecs/common/unix.conf:
/opt/local/libexec/qt5/mkspecs/common/mac.conf:
/opt/local/libexec/qt5/mkspecs/common/macx.conf:
/opt/local/libexec/qt5/mkspecs/common/sanitize.conf:
/opt/local/libexec/qt5/mkspecs/common/gcc-base.conf:
/opt/local/libexec/qt5/mkspecs/common/gcc-base-mac.conf:
/opt/local/libexec/qt5/mkspecs/common/clang.conf:
/opt/local/libexec/qt5/mkspecs/common/clang-mac.conf:
/opt/local/libexec/qt5/mkspecs/qconfig.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_macextras.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdf.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_repparser.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_scxml.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webengine.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/local/libexec/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/local/libexec/qt5/mkspecs/features/qt_functions.prf:
/opt/local/libexec/qt5/mkspecs/features/qt_config.prf:
/opt/local/libexec/qt5/mkspecs/macx-clang/qmake.conf:
/opt/local/libexec/qt5/mkspecs/features/spec_post.prf:
../.qmake.stash:
/opt/local/libexec/qt5/mkspecs/features/exclusive_builds.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/sdk.prf:
/opt/local/libexec/qt5/mkspecs/features/toolchain.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/toolchain.prf:
/opt/local/libexec/qt5/mkspecs/features/default_pre.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/default_pre.prf:
/opt/local/libexec/qt5/mkspecs/features/resolve_config.prf:
/opt/local/libexec/qt5/mkspecs/features/default_post.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/default_post.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/objective_c.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/mac.prf:
/opt/local/libexec/qt5/mkspecs/features/warn_on.prf:
/opt/local/libexec/qt5/mkspecs/features/qt.prf:
/opt/local/libexec/qt5/mkspecs/features/resources_functions.prf:
/opt/local/libexec/qt5/mkspecs/features/resources.prf:
/opt/local/libexec/qt5/mkspecs/features/moc.prf:
/opt/local/libexec/qt5/mkspecs/features/unix/opengl.prf:
/opt/local/libexec/qt5/mkspecs/features/uic.prf:
/opt/local/libexec/qt5/mkspecs/features/unix/thread.prf:
/opt/local/libexec/qt5/mkspecs/features/qmake_use.prf:
/opt/local/libexec/qt5/mkspecs/features/file_copies.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/rez.prf:
/opt/local/libexec/qt5/mkspecs/features/mac/asset_catalogs.prf:
/opt/local/libexec/qt5/mkspecs/features/testcase_targets.prf:
/opt/local/libexec/qt5/mkspecs/features/exceptions.prf:
/opt/local/libexec/qt5/mkspecs/features/yacc.prf:
/opt/local/libexec/qt5/mkspecs/features/lex.prf:
securevault.pro:
resources.qrc:
/opt/local/libexec/qt5/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/local/libexec/qt5/lib/QtGui.framework/Resources/QtGui.prl:
/opt/local/libexec/qt5/lib/QtNetwork.framework/Resources/QtNetwork.prl:
/opt/local/libexec/qt5/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile securevault.pro

qmake_all: FORCE

SecureVault.app/Contents/PkgInfo: 
	@test -d SecureVault.app/Contents || mkdir -p SecureVault.app/Contents
	@$(DEL_FILE) SecureVault.app/Contents/PkgInfo
	@echo "APPL????" > SecureVault.app/Contents/PkgInfo
SecureVault.app/Contents/Resources/empty.lproj: 
	@test -d SecureVault.app/Contents/Resources || mkdir -p SecureVault.app/Contents/Resources
	@touch SecureVault.app/Contents/Resources/empty.lproj
	
SecureVault.app/Contents/Info.plist: 
	@test -d SecureVault.app/Contents || mkdir -p SecureVault.app/Contents
	@$(DEL_FILE) SecureVault.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.SecureVault,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.SecureVault,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,icon.png,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},icon.png,g" -e "s,@EXECUTABLE@,SecureVault,g" -e "s,@LIBRARY@,SecureVault,g" -e "s,\$${EXECUTABLE_NAME},SecureVault,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/local/libexec/qt5/mkspecs/macx-clang/Info.plist.app >SecureVault.app/Contents/Info.plist
SecureVault.app/Contents/Resources/icon.png: icon.png
	@test -d SecureVault.app/Contents/Resources/ || mkdir -p SecureVault.app/Contents/Resources/
	@$(DEL_FILE) SecureVault.app/Contents/Resources/icon.png
	@$(COPY_FILE) icon.png SecureVault.app/Contents/Resources/icon.png

all: Makefile \
		SecureVault.app/Contents/PkgInfo \
		SecureVault.app/Contents/Resources/empty.lproj \
		SecureVault.app/Contents/Info.plist \
		SecureVault.app/Contents/Resources/icon.png SecureVault.app/Contents/MacOS/SecureVault

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/local/libexec/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents login.h sv_main.h rojer_home.h rojer_encrypt.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp rojer_encrypt.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r SecureVault.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/opt/local/libexec/qt5/bin/rcc \
		icon.png \
		text.png \
		image.png \
		other.png
	/opt/local/libexec/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/local/libexec/qt5/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /opt/local/libexec/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_sv_main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sv_main.cpp
moc_sv_main.cpp: sv_main.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QDialog \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QTextEdit \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qtextedit.h \
		rojer_home.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qmessagebox.h \
		login.h \
		moc_predefs.h \
		/opt/local/libexec/qt5/bin/moc
	/opt/local/libexec/qt5/bin/moc $(DEFINES) --include /Users/gowrisankara/Desktop/SV/SV-PROJECT/moc_predefs.h -I/opt/local/libexec/qt5/mkspecs/macx-clang -I/Users/gowrisankara/Desktop/SV/SV-PROJECT -I/opt/local/include -I/opt/local/include/openssl -I/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers -I/opt/local/libexec/qt5/lib/QtGui.framework/Headers -I/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers -I/opt/local/libexec/qt5/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/local/libexec/qt5/lib sv_main.h -o moc_sv_main.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp sv_main.cpp \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QFile \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qfile.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QByteArray \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QCryptographicHash \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qcryptographichash.h \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/QHttpMultiPart \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/QHttpPart \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QFileDialog \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QFileInfo \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qfileinfo.h \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/QNetworkReply \
		/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QJsonValue \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qjsonvalue.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QJsonObject \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QJsonArray \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qjsonarray.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QAction \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qaction.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QInputDialog \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QMenu \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qmenu.h \
		/opt/local/libexec/qt5/lib/QtGui.framework/Headers/QCloseEvent \
		/opt/local/libexec/qt5/lib/QtGui.framework/Headers/qevent.h \
		sv_main.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QDialog \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QTextEdit \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qtextedit.h \
		rojer_home.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qmessagebox.h \
		login.h \
		rojer_encrypt.h \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/QApplication \
		/opt/local/libexec/qt5/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

rojer_encrypt.o: rojer_encrypt.cpp rojer_encrypt.h \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/QByteArray \
		/opt/local/libexec/qt5/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/local/include/openssl/evp.h \
		/opt/local/include/openssl/macros.h \
		/opt/local/include/openssl/opensslconf.h \
		/opt/local/include/openssl/configuration.h \
		/opt/local/include/openssl/opensslv.h \
		/opt/local/include/openssl/types.h \
		/opt/local/include/openssl/e_os2.h \
		/opt/local/include/openssl/safestack.h \
		/opt/local/include/openssl/stack.h \
		/opt/local/include/openssl/core.h \
		/opt/local/include/openssl/core_dispatch.h \
		/opt/local/include/openssl/indicator.h \
		/opt/local/include/openssl/params.h \
		/opt/local/include/openssl/bn.h \
		/opt/local/include/openssl/crypto.h \
		/opt/local/include/openssl/cryptoerr.h \
		/opt/local/include/openssl/symhacks.h \
		/opt/local/include/openssl/cryptoerr_legacy.h \
		/opt/local/include/openssl/ebcdic.h \
		/opt/local/include/openssl/bnerr.h \
		/opt/local/include/openssl/bio.h \
		/opt/local/include/openssl/bioerr.h \
		/opt/local/include/openssl/evperr.h \
		/opt/local/include/openssl/objects.h \
		/opt/local/include/openssl/obj_mac.h \
		/opt/local/include/openssl/asn1.h \
		/opt/local/include/openssl/asn1err.h \
		/opt/local/include/openssl/objectserr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rojer_encrypt.o rojer_encrypt.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_sv_main.o: moc_sv_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sv_main.o moc_sv_main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

